server {
  listen 80;
  client_max_body_size 10m;

  location /auth/v1/ {
    proxy_pass http://auth:9999/;
    proxy_set_header Host $host;
  }

  location /rest/v1/ {
    proxy_pass http://rest:3000/;
    proxy_set_header Host $host;
  }
}
